### ISSUE TITLE
Add Web Share and Web Share Target APIs to charter

### ISSUE THREAD

**Issue by mgiuca** [w3c/WebPlatformWG#105]
Hi,

Spinning off from w3c/dap-charter#58, we would like Web Platform WG to consider adopting [Web Share](https://wicg.github.io/web-share/) and [Web Share Target](https://wicg.github.io/web-share-target/) APIs into the charter.

The [Web Share](https://wicg.github.io/web-share/) API has been in WICG for a long time now, and is fairly mature. While it only has one implementation (Chrome), it had a lot of interest from other vendors, and we would like to move it onto a standards track. This adds a single new method, `navigator.share`, which allows a web page to trigger a share event to an arbitrary destination of the user's choice. It is up to the implementation what choices are available; typically it would go into the host OS's share system.

The companion API, Web Share Target, [Web Share Target](https://wicg.github.io/web-share-target/), allows sites to register to receive shared data, from Web Share but also from the host OS's share system. This API is not as far along, with a number of outstanding issues on the spec draft, and while there are prototype implementations in Chrome, nothing has been released. There is more controversy over the syntax and nature of the API, and it's generally a bit more complex. Eventually, it makes sense for WST to become part of the Manifest API, and the spec has been written with that in mind.

Therefore, I think both of these APIs are a good fit for the Web Platform WG (which also hosts the Manifest API).

**Comment by LJWatson** [comment]
Thanks @mgiuca. Are there statements of intent to commit (for either API) from other implementors you can point to?

**Comment by mgiuca** [comment]
* Web Share
  * [Mozilla position discussion](https://github.com/mozilla/standards-positions/issues/27). There is support from many people within Mozilla, but note the objection from @tantek, primarily that Web Share would be harmful without Web Share Target (partly why I'm asking to charter both of these at the same time).
  * [Apple bug](https://bugs.webkit.org/show_bug.cgi?id=171100). No intent to commit but they have said it's "interesting" and are tracking it.
* Web Share Target
  * Mozilla position: No explicit position, but note the above objection that would be resolved by Web Share Target.

No other public signals that I am aware of.

**Comment by LJWatson** [comment]
This is on the agenda for TPAC (tracked as #121)

**Comment by marcoscaceres** [comment]
WebShare is in the upcoming WebApps charter, so closing.
