### ISSUE TITLE
Agendas: TPAC 2018

### ISSUE THREAD

**Issue by LJWatson** [w3c/WebPlatformWG#120]
Agendas for the Web Platform WG meetings at [TPAC 2018](https://www.w3.org/2018/10/TPAC/), on Monday 22 and Friday 26 October, plus the Editing TF (Task Force) meeting on Tuesday 23 October and Web Components meeting on Thursday 25 October.

## Monday October 22
Room: Rhône 2, Level 1 - Rhône Pasteur
[Web Platform WG Day 1 minutes](https://www.w3.org/2018/10/22-WebPlat-minutes.html)

* 9.30AM: Welcome and housekeeping
* 9:45AM: [Intersection Observer](https://w3c.github.io/IntersectionObserver/) (Stefan Zager):
  * w3c/IntersectionObserver#95
* 10.00AM: [UI Events](https://w3c.github.io/uievents/) (Gary Kacmarcik):
  * [I18n issues](https://github.com/w3c/uievents/issues?utf8=%E2%9C%93q=is%3Aissue+is%3Aopen+label%3Ai18n-comment)
  * Merging [WICG - Keyboard Map](https://wicg.github.io/keyboard-map/) and [Keyboard Lock](https://w3c.github.io/keyboard-lock/)
  * Dividing [Keyboard Events Code Values](https://w3c.github.io/uievents-code/) and [Keyboard Events Key Values](https://w3c.github.io/uievents-key/) into Levels
  * Updating [UI Events](https://w3c.github.io/uievents/) to include procedural algorithms
  * Special handling for AltGraph on Windows
* 11AM: Break
* 11.30AM: [DOM Parsing and Serialization](https://w3c.github.io/DOM-Parsing/) (Travis Leithead)
* 12PM: [IndexedDB 3.0](https://w3c.github.io/IndexedDB/) (Daniel Murphy):
  * [IndexedDB.databases()](https://github.com/w3c/IndexedDB/pull/240)
  * [Transaction commit()](https://github.com/w3c/IndexedDB/pull/242)
  * [IndexedDB Observers](https://github.com/WICG/indexed-db-observers)
  * [WICG - lifecycle](https://wicg.github.io/page-lifecycle/spec.html) integration
  * [async local storage](https://domenic.github.io/async-local-storage/)
* 12:45PM: Lunch
* 2.15PM: Meeting with APA WG (Janina Sajka):
  * [Personalization Semantics](https://www.w3.org/TR/personalization-semantics-1.0/)
* 3PM:  [WICG - Cookie Store](https://github.com/wicg/cookie-store) (Marijn Kruisselbrink)
* 3.30PM: [WICG - Web Locks API](https://github.com/inexorabletash/web-locks) (Ben Kelly)
* 4PM: Break
* 4.30PM: Web Locks overflow
* 5.00 PM: requestAnimationFrame timing
* 5.30PM: Meeting ends

## Tuesday October 23 (Editing TF)
Room: Saint Clair 3A, Level 2 - Saint-Clair
[Editing TF minutes](https://www.w3.org/2018/10/23-WebPlat-minutes.html)

* 9.30AM: Welcome and housekeeping
* 9.45AM: [Clipboard API and Events](https://w3c.github.io/clipboard-apis/) (Gary Kacmarcik):
  * Additional clipboard mime types
  * Mime types to support directly
  * Image and delayed content generation proposal
  * DataTransfer for clipboard data
  * "Pickled" format for browsers
* 11AM: Break
* 11.30AM: [Input Events](https://rawgit.com/w3c/input-events/v1/) [I18n issues](https://github.com/w3c/input-events/issues?utf8=%E2%9C%93q=is%3Aissue+is%3Aopen+label%3Ai18n-comment)
* 12PM: contenteditable-disabled DOM API attribute (johannes Wilm):
  * w3c/editing#176
* 12.45PM: Deprecate document.designMode (Johannes Wilm):
  * w3c/editing#177
* 1PM: Lunch
* 2.30PM: Apply text transformation on copy (Johannes Wilm):
  * w3c/editing#178
* 3PM: Adding custom menu items to editing context menus (Johannes Wilm):
  * w3c/editing#176
* 3.45PM: Editing UI on mobile (Piotr Koszulinski). 
* 4PM: Break
* 4.30PM: Range plus selection decorations (Piotr Koszulinski):
  * w3c/editing#166
* 5PM: [Accessibility Object Model (AOM)](https://github.com/WICG/aom/blob/gh-pages/explainer.md) (Gary Kacmarcik):
  * AOM input event types
  * Where should the AOM input event types spec live?
  * Moving the IDL (and only the IDL) for `inputType` from Input Events into UI Events
* 5.30PM: Meeting ends

## Thursday October 25 (Web Components)
Room: Lumière Lounge, Level -1 - Lumière |   | 1
[Web Components Contributors minutes](https://www.w3.org/2018/10/25-WebComponents-minutes.html)

* 9.30AM: Welcome and housekeeping
* 9.45AM: Web Components TBC
* 11AM: Break
* 11.30AM: Web Components TBC
* 1.30PM: Meeting ends

## Friday October 26
Room: Forum 2, Level -2 - Forums
[Web Platform WG Day 2 minutes](https://www.w3.org/2018/10/26-WebPlat-minutes.html)

* 9.30AM: Welcome and housekeeping
* 9.45AM: [Push API](http://w3c.github.io/push-api/) (Peter Beverloo)
* 10AM: [Web App Manifest](https://www.w3.org/TR/apPManifest/) - [agenda](https://github.com/w3c/manifest/wiki/TPAC-2018-Agenda) (Matt Giuca)
* 10:15AM: WebPlat WG:
  * Test driven spec develoPMent
  * Working better together
* 11AM: Break
* 11.30AM: [WICG - Writable Files](https://github.com/WICG/writable-files/blob/master/EXPLAINER.md) (Marijn Kruisselbrink)
* 12PM: [WICG - Web Share](https://github.com/WICG/web-share) and [WICG - Web Share Target](https://github.com/WICG/web-share-target) (Eric Willigers, Matt Giuca)
* 12.30PM: [WICG - Badging Web API](https://github.com/WICG/badging) (Matt Giuca)
* 1PM: Lunch
* 2PM: [Gamepad API](https://w3c.github.io/gamepad/) (Steve Agoston):
   * Taking v1 to Recommendation
  * v2 roadmap and extensions

* 2.30PM: [Web Components](https://github.com/w3c/webcomponents/issues/763#issuecomment-427177002) (Ryosuke Niwa):
* 4PM: Break
* 4.30PM: Web Components (continued) (Ryosuke Niwa):
* 5.30PM: Meeting ends

## Meeting logisttics
IRC channel: [#webplat](irc://irc.w3.org/#webplat)  on the irc.w3.org webserver. There is a web-based client at https://irc.w3.org 

[Remote dial-in info](https://lists.w3.org/Archives/Member/w3c-archive/2018Sep/0076.html) (W3C member-only. Ping on IRC for help getting it)

**Comment by szager-chromium** [comment]
I'd like a 15-minute chunk on Monday to discuss this issue:

https://github.com/w3c/IntersectionObserver/issues/95

**Comment by pwnall** [comment]
I would like a 30-minute block on Monday to discuss the Cookie Store (a.k.a. Async Cookies) API -- https://github.com/wicg/cookie-store

**Comment by pwnall** [comment]
I would like a 30-minute block to on Monday to discuss the Web Locks API -- https://github.com/inexorabletash/web-locks

**Comment by dmurph** [comment]
I'd like a 45-minute block on Monday to discuss IndexedDB 3.0. I would like to discuss:
* IndexedDB.[databases()](https://github.com/w3c/IndexedDB/pull/240)
* Transaction [commit()](https://github.com/w3c/IndexedDB/pull/242), and other options for giving users more control over commit time. Possibly reference [lifecycle](https://wicg.github.io/page-lifecycle/spec.html) integration.
* putAll
* IndexedDB [Observers](https://github.com/WICG/indexed-db-observers)

**Comment by LJWatson** [comment]
Agendas have been updated with requests to date.

**Comment by rniwa** [comment]
I'd like to request two two-hour (four hour total) meetings to discuss web components on Friday. Specifically, resolving issues with the existing features (e.g. [history management in shadow DOM](https://github.com/w3c/webcomponents/issues/184), [ID reference in SVG](https://github.com/w3c/webcomponents/issues/179), [defining ways to provide custom-element only API](https://github.com/w3c/webcomponents/issues/758)).

**Comment by LJWatson** [comment]
@rniwa I've found three hours on Friday for this. If you really need the extra hour, we can take 30 minutes off the lunch break and add 30 minutes to the end of the day. Let me know?

**Comment by LJWatson** [comment]
@pwnall and @garykac, can your discussions of Web Lock be combined?

**Comment by LJWatson** [comment]
@johanneswilm I've begun adding things to the Editing TF agenda, based on requests from @garykac and Grisha. I've estimated times for the requests I know about, but let me know if they seem unrealistic and/or what else you want to put on the Tuesday agenda. Thanks.

**Comment by garykac** [comment]
Web Locks and Keyboard Lock are not the same.

There isn't a lot to discuss (~15min) WRT Keyboard Lock other than merging the 2 Keyboard specs (Lock and Map) into a single document.

**Comment by LJWatson** [comment]
Thanks for confirming/clarifying @garykac. It's possible I've been staring at these agendas too ong today!

**Comment by rniwa** [comment]
@LJWatson Thanks for the time slot! I'd solicit more topics related to web components as I'm sure there are more to discuss at TPAC.

**Comment by LJWatson** [comment]
The agendas for Monday and Friday are full now.

Ping @sagoston to point out that Gamepad has now moved to Monday, per your original request.

Ping @michael-n-cooper to point out that the meeting time with APA has changed, largely in response to the discussion on the APA call this week.

**Comment by annevk** [comment]
I think it would be good to have more time for web components given how https://github.com/w3c/webcomponents/issues/763 grows. If there's no time on the agenda left we should schedule some kind of breakout on Wednesday as well perhaps.

**Comment by LJWatson** [comment]
@annevk the agenda for both Monday and Friday is pretty crammed already. The best I can come up with would be to shorten lunch on Friday by 30 minutes, extend the finishing time by 30 minutes, and break the one 30 minute break into two 15 minute breaks, but that seems pretty hard-core for a Friday.

Otherwise there might be wriggle room on Tuesday. If @johanneswilm can let me know whether the last hour is needed by the Editing TF, that would be helpful.

Otherwise it may have to be a breakout session on Wednesday, as you suggest.

**Comment by johanneswilm** [comment]
There is no wriggle room on Tuesday. Only reason we are keeping some points open still is that more different groups should be able to have their priorities represented that day.
Also, from the JS side, there is little overlap with the other groups. Participants travel there to talk about their editing concerns and don't care much about other types of web apps.

**Comment by LJWatson** [comment]
Fair enough @johanneswilm. Thanks for letting me know.

@annevk @rniwa let me know what you want to do?

**Comment by annevk** [comment]
I guess there's no possibility of having multiple rooms? I'm not sure how much overlap there is between the topics, but some of it should be able to be done in parallel.

**Comment by johanneswilm** [comment]
I think the Editing Taskforce meeting could be done in parallel to the other meetings, if the rooms are available. As I understood it, there will only be a small room for the Editing Taskforce on Tuesday. Is that correct?

**Comment by chaals** [comment]
Unfortunately no, there aren't multiple rooms available to the best of my knowledge. (I will ask if there is a possibility of one though).

**UPDATE** I made the request. We'll see...

**Comment by LJWatson** [comment]
@annevk @rniwa We've asked for more space. It's uncertain whether we'll get it at this stage, but there is a slight possibility of time/space on Thursday morning. We should know by the end of the month.

**Comment by rniwa** [comment]
Thanks, @LJWatson!

**Comment by LJWatson** [comment]
@rniwa  and @annevk , we've been able to find time and space on Thursday (see agenda placeholder in my original comment). There will be space for 15 people, but no phone bridge for remote dial in.

Please let me know what items you'd like added to the agenda? I'll be sending out a message to everyone who has requested participation soon, so it'd be good to have some idea in the next couple of days. Thanks.

**Comment by rniwa** [comment]
@LJWatson : the full list of agenda is listed at: https://github.com/w3c/webcomponents/issues/763#issuecomment-423719623 I'll ask who can attend Tuesday / Friday sessions and which topic should be covered on which day.

**Comment by domenic** [comment]
Can we add a sub-bullet under the IndexedDB discussion for [async local storage](https://domenic.github.io/async-local-storage/)?

**Comment by mkruisselbrink** [comment]
I updated the cookie store and web locks agenda items to have respectively my and @wanderview's name associated with them, since @pwnall won't be at TPAC after all.

**Comment by marcoscaceres** [comment]
@domenic, done.

**Comment by marcoscaceres** [comment]
@mgiuca, can you do the Web Manifest update on Tuesday?

**Comment by marcoscaceres** [comment]
sorry, I mean Friday at 10am.

**Comment by mgiuca** [comment]
Yep, I can speak on Web App Manifest but does that mean you won't be there? If so, we should work out in advance what you want us to talk about.

**Comment by marcoscaceres** [comment]
> Yep, I can speak on Web App Manifest but does that mean you won't be there? If so, we should work out in advance what you want us to talk about.

**Comment by marcoscaceres** [comment]
> Yep, I can speak on Web App Manifest but does that mean you won't be there? 

I'll be there, but Chairing. 

> If so, we should work out in advance what you want us to talk about.

The significant things that have landed in the last year. Also, whatever is affecting developers. And we need to decide how we get this spec to "CR" (i.e., who is going to do the test suite, etc.).

**Comment by LJWatson** [comment]
@rniwa  @annevk  @domenic   No-one is [registered](https://www.w3.org/2002/09/wbs/35125/TPAC2018/registrants#WebComp) to attend the Thursday meeting. It would be helpful to have some sense of who expects to be there if possible - especially since we had to go looking for the extra space. Thanks.

**Comment by annevk** [comment]
@johndai1984, @smaug---- , and I will be there for Mozilla. I think I signed up for something else since the agenda wasn't clear at that point.

**Comment by rniwa** [comment]
Hm... the questionnaire says the registration is closed. Where can I register myself to show up in that list? FWIW, I'd definitely be attending the Thursday session.

> This questionnaire is closed since 14 October 2018. Inform your Team contact if you think it should still be open. You can also see the results of this questionnaire.

**Comment by smaug----** [comment]
There is some pointer events stuff too on Thursday, so I probably need to spend some time there.

**Comment by LJWatson** [comment]
@rniwa registration has closed, but just noting names here will do the trick.

**Comment by rniwa** [comment]
@LJWatson : Okay, thanks for the clarification. I'm attending the full morning session on Thursday.

**Comment by LJWatson** [comment]
We've had a last minute request to move the Gamepad discussion to Friday. The simplest way to do this would be to move it to 10.15am (and move the test driven development and working better together discussions to Monday).

At this stage, members of the WG may have planned their week to include the Gamepad discussion on the Monday. If moving the discussion at this stage will complicate things for anyone, please comment here by 2pm UTC on Friday 19th Oct.

**Comment by cwilso** [comment]
It would be quite unfortunate to move the Gamepad discussion to Friday, as it will conflict with the Immersive Web WG/CG meeting then (and I know several of us are keen to participate).  Barring that, it would be handy to try to coordinate with the IWWG schedule (https://github.com/immersive-web/administrivia/blob/master/TPAC-2018/schedule.md).

**Comment by marcoscaceres** [comment]
Let’s stick with Friday. We will find a way to make it work.

**Comment by gsnedders** [comment]
> and move the test driven development and working better together discussions to Monday

If you want anyone from WPT land, including several of people who were involved with the working mode changes in the WHATWG, it can't be on Monday/Tuesday.

**Comment by marcoscaceres** [comment]
We will do it on Friday. @gsnedders, you wanna present with me? I can show how we do it really successfully in Payments - but would love some support from a wpt person to talk about the infrastructure (e.g., how things get upstreamed from browser vendors, wpt.fyi, etc.). Anything that helps convince people that this is an awesome ideas with massive benefits💡

**Comment by cwilso** [comment]
@marcoscaceres When you say "it" are you talking about test driven development or gamepad?

**Comment by marcoscaceres** [comment]
It === test drive development. But I want to keep that short too, so we can get back some time for Gamepad. I don’t think there are too many people that are not convinced about TDD for specs. I just want to show how we are going to do it going forward.

**Comment by mgiuca** [comment]
I have a number of slots in my name on Friday, which I would be happy to shuffle around if that helps.

**Comment by marcoscaceres** [comment]
Thanks @mgiuca. We will squeeze everything in, don’t worry. We just need to squeeze a few topics by 5 mins here and there so we can still discuss Gamepad on Friday.

**Comment by LJWatson** [comment]
@marcoscaceres  It looks like moving it to Friday is a problem for members of the IW WG, per @Cwilso's comment above.

**Comment by tomalec** [comment]
If there is still any space left, I'd love to attend Thursday meeting as well.

**Comment by LJWatson** [comment]
There is space for 15 people on Thursday, so there should be plenty of room @tomalec.

**Comment by LJWatson** [comment]
Talked with @Cwilso, and the least worst option seems to be to take 30 minutes off our lunch break, and schedule the Gamepad discussion at 2PM on Friday. Thank you to the IW WG for being willing to shuffle their agenda too.

Thanks for the offer to move your items @mgiuca, but I think we're ok.
 
**Note:** to avoid a gap in the middle of Monday afternoon, I've bumped the Cookie Store discussion up to 3PM (ping @mkruisselbrink ), and the Web Locks discussion up to 3.30pm (ping @inexorabletash  (since I can't find Brian kelly)).

Further changes to the agenda will only be possible with the generous application of tequila...

See everyone on Monday!

**Comment by pwnall** [comment]
@LJWatson Thank you for the updates. Ben Kelly (presenting Web Locks) is @wanderview

**Comment by dmurph** [comment]
@tabatkins isn't available on Friday and he said he has a lot of domain knowledge around the ShadowDOM topic scheduled that day and he would like to attend. Can we somehow move that to this afternoon?

**Comment by mkruisselbrink** [comment]
Both today and on Friday it appears that both breaks are scheduled outside of the official "groups may break any time between xx and yy" time blocks. Is that intended?

**Comment by tabatkins** [comment]
For the SVG IDs in Shadow DOM discussion, I won't be around on Friday (I had meetings last week in Paris, and wanted to minimize my time away from home), but I've had proposals for fixing this exact problem more widely in CSS.

If we could reschedule to any other day, that would be great, but if not, please [consider my last comments on the topic](https://github.com/w3c/webcomponents/issues/179#issuecomment-410071854).

**Comment by dmurph** [comment]
The WebPlat group reports that they would prefer to do the SVG IDs in Shadow DOM discussion on Thursday - @tabatkins will be available that day. So let's schedule some time on that day for that discussion. For those who are running/attending, you can figure out if you want time on both days or one day.

**Comment by plehegar** [comment]
fyi, the HTML WHATWG Editors will be available on Thursday 2PM-6PM (same room as web compenents)to have a workshop to explore potential HTML 5.3 features and help map them into issues and pull requests.

**Comment by mgiuca** [comment]
Agenda for Web App Manifest tomorrow: https://github.com/w3c/manifest/wiki/TPAC-2018-Agenda

**Comment by chaals** [comment]
thanks @mgiuca - added the link to the agenda at the top, too

**Comment by marcoscaceres** [comment]
Meeting adjourned.

**Comment by annevk** [comment]
(It's still going strong.)
