### ISSUE TITLE
CFC: Mark View-Mode Media Feature Obsolete

### ISSUE THREAD

**Issue by LJWatson** [w3c/WebPlatformWG#121]
This is a Call For Consensus (CFC) to mark [View-Mode Media Feature](https://www.w3.org/TR/view-mode/) Obsolete.

The View-Mode specification is maintained by the Web Platform WG. It was not implemented in browsers, only in widget engines. View-Mode Media Feature is part of the [Widget Specs](https://www.w3.org/TR/?title=widget), which the TAG has [marked for Obsoletion](https://github.com/w3ctag/obsoletion/issues/3).

The term "Obsolete" is defined in the [W3C Process](https://www.w3.org/2018/Process-20180201/#rec-rescind):
>"W3C may obsolete a Recommendation, for example if the W3C Community decides that the Recommendation no longer represents best practices, or is not adopted and is not apparently likely to be adopted. An Obsolete Recommendation may be restored to normal Recommendation, for example because despite marking it Obsolete the specification is later more broadly adopted.">

If you agree that View-Mode Media Feature should be marked Obsolete, please post a "thumbs up" reaction to this comment. If you disagree, please post a "thumbs down" reaction to this comment, and give your reasons in the comments.

If you do not respond, it will be taken as silent agreement with the proposal to mark View-Mode Media Feature Obsolete. Actual responses are preferred however. 

Please respond to this CFC by the end of day on Friday 3rd August 2018.

**Comment by frivoal** [comment]
Seems to me that some of this could be recycled for the sake of PWA / fullscreen mode, but it should be revisited for that purpose, rather than assumed to be fit to purpose as-is. Until that happens and implementation interest comes along, Obsolete seems right.

**Comment by LJWatson** [comment]
This CFC passes with only positive messages of support (here and by email) and no objections.

**Comment by marcoscaceres** [comment]
@frivoal, about reuse... we came up with a new one (`display-mode` media feature):
https://www.w3.org/TR/appmanifest/#display-modes
