### ISSUE TITLE
Add Keyboard Lock and Keyboard Map to charter

### ISSUE THREAD

**Issue by LJWatson** [w3c/WebPlatformWG#122]
Request from @GaryKac to add [Keyboard Lock](https://w3c.github.io/keyboard-lock/) and [Keyboard Map](https://wicg.github.io/keyboard-map/) to the WebPlat WG charter.

**Comment by marcoscaceres** [comment]
Both are well aligned with existing events  work. Do they have interest and/or implementation commitment from multiple browsers?

**Comment by marcoscaceres** [comment]
Moved them to WICG.
