### ISSUE TITLE
Add the User Input of Mathematics to Charter

### ISSUE THREAD

**Issue by AdamSobieski** [w3c/WebPlatformWG#123]
Web Platform Working Group,

For your consideration, I would like to indicate an opportunity to add the [user input of mathematics](https://discourse.wicg.io/t/proposal-user-input-of-mathematics/2998) as a new Working Group deliverable.

As envisioned, group discussion topics would include: (1) hypertext document markup for providing users with mathematical and notational user input, (2) mathematical and notational user input scenarios pertaining to forms and to `contenteditable` content, (3) a JavaScript API for utilization of and interoperation with mathematical and notational user input controls provided by websites, browsers, operating system platforms and third-party software vendors.

Input modalities of mathematical and notational user input controls include keyboard and mouse, handwriting recognition and speech recognition. The JavaScript API envisioned would encompass providing such user input controls with contextual recognition hints and obtaining resultant data, expressions and graphics.

In the course of our [discussion](https://discourse.wicg.io/t/proposal-user-input-of-mathematics/2998) at the WICG, we considered that implementers included the implementers of such user input controls. One such implementer, Wiris, presented [some issues](https://discourse.wicg.io/t/proposal-user-input-of-mathematics/2998/5) which were addressed throughout the remainder of the discussion.

The user input of mathematics is an important topic. The user input of mathematics facilitates scholarly and scientific communication as well as education, providing for new varieties of science, technology, engineering and mathematics exercises and activities.

Thank you for considering the user input of mathematics as a new Working Group deliverable.

**Comment by LJWatson** [comment]
Thanks @AdamSobieski.

The next step for your proposal is to begin working on a draft version of the spec, and incubate it within the [WICG](https://github.com/WICG) until it is ready to transition to a WG. Factors that suggest a spec is ready to transition include: a draft version of the spec that has reached a degree of maturity, evidence of interest to implement from at least two key implementors, evidence that there is a community driving the spec forward.


Without these things, we can't consider adding a spec to the WebPlat charter.

@MarcosCaceres @YoavWeiss and @Cwilso are the WICG chairs, and they'll be able to point you in the right direction.

**Comment by marcoscaceres** [comment]
Thanks @LJWatson. @AdamSobieski, yes, please start here:
https://github.com/wicg/admin#contributing-new-proposals

And then spin up a thread here:
https://discourse.wicg.io

If the proposal gets legs, we can move the work over to the right working group in the future.
