### ISSUE TITLE
Promote File Handling to WICG

### ISSUE THREAD

**Issue by fallaciousreasoning** [w3c/WebPlatformWG#127]
The [File Handling](https://github.com/ewilligers/file-handling/blob/master/explainer.md) proposal was briefly [discussed](https://www.w3.org/2018/10/26-webplat-minutes.html#item05) at TPAC.

The proposal would be useful for online image manipulations tools, computer aided design tools and document editors.

We would like to refine this proposal in the context of WICG. Contributions and feedback from other browser vendors would be much appreciated (e.g. @marcoscaceres  @aliams  @hober do you have any thoughts?).

**Comment by aliams** [comment]
I think we should definitely move this to the WICG for further collaboration!

**Comment by marcoscaceres** [comment]
Agree, we should definitely discuss! step one would be to spin up a Discourse thread: http://discourse.wicg.io/ and then close this issue to avoid fragmenting the discussion. 

I think @annevk concerns from TPAC probably need addressing so adding some straw-persons around UX would be helpful.

**Comment by fallaciousreasoning** [comment]
There's an existing discourse thread [here](https://discourse.wicg.io/t/proposal-ability-to-register-file-handlers/3084/)

**Comment by ewilligers** [comment]
Thanks everyone. The File Handling repo is now in WICG: https://github.com/WICG/file-handling 

This issue can be closed.
