### ISSUE TITLE
Gamepad-Lock API

### ISSUE THREAD

**Issue by pyalot** [w3c/WebPlatformWG#2]
Edge is coming to Xbox One. The gamepad-API supports gamepads (and other HIDs) in browsers.

Ordinarily there are no browser actions assigned to gamepads, and so users of the gamepad API are free to use all inputs on these devices.

But on platforms that primarily interact with the browser trough gamepads, there is a problem, most of the inputs are assigned to browser actions (clicking, navigation, back, forward, etc.). In that situation, the gamepad API could not sensibly be supported because most inputs on a gamepad couldn't be used (and this conflict would probably lead UA-vendors to skip on that API).

Should there be a gamepad-lock api analogous to how there is a pointerlock-api?

**Comment by AFBarstow** [comment]
FYI, the [gamepad spec](https://w3c.github.io/gamepad/) has in its [feature requests](https://github.com/w3c/gamepad/blob/gh-pages/FeatureRequests.md) document, there are some links to previous discussions about locking. Is this (at least kinda') what you are after Florian? If so, perhaps you should followup with a discussion/issue in the gamepad repo (and close this issue).

@sgraham @luser

**Comment by pyalot** [comment]
The feature request in the gamepad spec for locking matches this request.
