### ISSUE TITLE
Move uievents meeting minutes data from w3c wiki to Github

### ISSUE THREAD

**Issue by AFBarstow** [w3c/WebPlatformWG#3]
The uievents/D3E group maintains a [meeting minutes wiki](https://www.w3.org/2008/webapps/wiki/Bi-weekly_meetings) at the W3C and since WPWG doesn't use that wiki, the relevant data should be moved to the [uievents repo](https://github.com/w3c/uievents).

@garykac @travisleithead - please take care of this or let us know what you want done and we'll find someone to do it.

**Comment by travisleithead** [comment]
OK, I've migrated our minutes over to GitHub. https://github.com/w3c/uievents/wiki/Meeting-Notes
