### ISSUE TITLE
Different ways to run a CFC?

### ISSUE THREAD

**Issue by LJWatson** [w3c/WebPlatformWG#38]
Calls For Consensus (CFC) are traditionally handled on the official email for the WG in question. It is possible that other ways to run a CFC are more efficient/easier/preferable/delete as applicable... Thoughts?

**Comment by marcoscaceres** [comment]
Few options: run a survey... or just let people use reactions in a GitHub issue thread.

**Comment by jfsiii** [comment]
+1 for opening an issue or PR (e.g. "Move 5.1 to CR") and tracking via comments & reactions.

**Comment by ZoeBijl** [comment]
CFC via GitHub would be good! Send a link to the list as backup. GitHub is easier to follow than mail for me. I know this is a personal preference, but still.

**Comment by chaals** [comment]
We dicussed this at TPAC, and again general consensus was that this is the way to do things. We'll run a formal CfC on it (oh, the irony) and assuming people keep liking it, put it into the workmode.

**Comment by LJWatson** [comment]
CFC has been opened with issue #80
