### ISSUE TITLE
Need PAG for "Web Components vs Extract Widget patent"?

### ISSUE THREAD

**Issue by AFBarstow** [w3c/WebPlatformWG#4]
This is a placeholder for W3C staff (@ylafon @siusin @plehegar @wseltzer) re the "Web Components vs Extract Widget patent" issue that was first raised in public-webapps in May 2015 https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0692.html 

Is a Patent Advisory Group needed for this? If yes, when will it be created?

**Comment by AFBarstow** [comment]
Ping @plehegar @siusin @ylafon

**Comment by siusin** [comment]
Web Components Patent Advisory Group <a href="https://lists.w3.org/Archives/Member/w3c-ac-members/2016JanMar/0008.html">Launched</a> @AFBarstow
