### ISSUE TITLE
Publish First Public Working Draft for HTML 5.2?

### ISSUE THREAD

**Issue by chaals** [w3c/WebPlatformWG#43]
This is (part of) a Call for Consensus, on the proposition:
Publish the [current editors draft of HTML 5.2](https://w3c.github.io/html/) as a W3C First Public Working Draft.

Feel free to add a thumbs-up here, or leave a comment, especially if you object to the proposal, up to and including 14 July 2016.

**Comment by LJWatson** [comment]
This CFC is now closed, per the <a href="https://lists.w3.org/Archives/Public/public-webapps/2016JulSep/0015.html">message posted to the WPWG</a>. The CFC passed with positive responses and no objections.
