### ISSUE TITLE
CFC to publish WebIDL-1 as a Proposed Recommendation

### ISSUE THREAD

**Issue by LJWatson** [w3c/WebPlatformWG#61]
This is a Call For Consensus (CFC) to publish <a href="https://ylafon.github.io/webidl/publications/pr-20160809.html">WebIDL-1</a> as a Proposed Recommendation (PR) [1].

Some editorial changes were made to the specification during the Candidate Recommendation (CR) period, but none that affects conformance. The <a href="https://www.w3.org/WebPlatform/WG/implementations/webidl-1/report/all.html">CR implementation
report</a> has the detail.

We are still exploring different ways of responding to a CFC. Please choose one of the following methods:
1. Reply by email to the thread (on public-webapps@w3.org).
2. +1/-1 or comment on this issue.

There is no need to use more than one method. The WP chairs will collate the results across all channels.

Please respond by end of day on Monday 22nd August. Positive responses are encouraged, but silence will be taken as consent with the proposal.

**Comment by adanilo** [comment]
+1

**Comment by LJWatson** [comment]
This CFC passed, and is now closed, per the <a href="https://lists.w3.org/Archives/Public/public-webapps/2016JulSep/0070.html">resolution</a> posted to public-webapps@w3.org.
