### ISSUE TITLE
CFC: Collect CFC responses on Github

### ISSUE THREAD

**Issue by LJWatson** [w3c/WebPlatformWG#80]
Hello WebPlat,

This is a Call For Consensus (CFC) on the proposal to collect responses to WebPlat CFCs on Github.

We have experimented with collecting responses to WebPlat CFCs on Github, by opening an issue on the repo for the specification in question. The experiment proved successful, and at TPAC the people present at the <a href="https://www.w3.org/2016/09/23-webapps-minutes.html#item09
">WebPlat meeting</a> agreed it was a good approach.

The approach would be to open a CFC issue on the Github repo for the specification, and send a notification to public-webapps@w3.org. Responses on Github would be strongly encouraged, although responses sent by email would not be excluded from the CFC.

If this CFC passes we will update the WebPlat <a href="https://github.com/w3c/WebPlatformWG/blob/gh-pages/WorkMode.md">work mode</a> accordingly.

Please respond to this CFC by end of day on Friday 7th October 2016. Positive responses (+1 on Github) are strongly preferred, but silence will be taken as implicit consent to the proposal.

**Comment by WebAppsWG** [comment]
+1

**Comment by adanilo** [comment]
+1
