### ISSUE TITLE
Update some links

### ISSUE THREAD

**Issue by xfq** [w3c/WebPlatformWG#81]
Hi,

It seems that [the revised charter has been approved](https://lists.w3.org/Archives/Public/public-webapps/2016OctDec/0019.html).

So, (at least) links to the charter in these files needs updating:

* https://github.com/w3c/WebPlatformWG/blame/33ff3b2f335d94afdb46ae83d433be8bf4098643/README.md#L3
* https://github.com/w3c/WebPlatformWG/blob/c11c65abb14d207a013332518e5ba5b65f0c39a3/WorkMode.md

Moreover, the FindText API was removed from the charter, so the following section can be removed: https://github.com/w3c/WebPlatformWG/blob/e1149040e6fd8d39899220ed7ca2fdda698ea90a/Coordination.md#web-annotations-wg

BTW, the "Git repositories" link in WorkMode.md[1] seems to be 404. (Or perhaps it is only visible to Group Members?)

[1] https://github.com/w3c/WebPlatformWG/blob/c11c65abb14d207a013332518e5ba5b65f0c39a3/WorkMode.md#bugs-issues-and-actions

**Comment by LJWatson** [comment]
Thanks @xfq

**Comment by xfq** [comment]
@LJWatson Thank you for updating the charter links! Can you fix the remaining two issues (FindText API and Git repositories) mentioned in the OP as well?
