### ISSUE TITLE
Broken Link on Web Platform Publication Status (PubStatus) web page

### ISSUE THREAD

**Issue by ericstamper** [w3c/WebPlatformWG#85]
The "Latest TR Publication" link for HTML5.2 is broken on the PubStatus.html page.

Specifically, line # 77 reads as:

`<td><a href=https://www.w3.org/TR/html52/">2017-01-17</a></td>`

and should be changed to:

`<td><a href="https://www.w3.org/TR/html52/">2017-01-17</a></td>`

**Comment by LJWatson** [comment]
With thanks @ericstamper
