### ISSUE TITLE
CFC: Publish WebIDL Level 2 as a FPWD

### ISSUE THREAD

**Issue by LJWatson** [w3c/WebPlatformWG#88]
This Call For Consensus (CFC) is to publish a First Public Working Draft (FPWD) of WebIDL Level 2, based on this [draft FPWD](https://www.w3.org/2017/08/webidl-fpwd-draft.html
).

Changes between WebIDL Level 1 and WebIDL Level 2 are shown in the Status section of the draft FPWD.

The intention is to point w3.org/tr/webidl to the FPWD when it is published.

Please respond to this CFC by the end of day on Friday 11th August 2017. Add a thumbs up/thumbs down, or a comment to this issue. If you choose not to respond it will be taken as silent consent to publish the FPWD of WebIDL Level 2. Your opinions are important though, so please take a minute to actively respond.

If you have technical comments on this specification, please file a [Github issue](https://github.com/heycam/webidl/issues/new).

**Comment by tobie** [comment]
As mentioned previously, and as discussed with @plehegar only a few days ago, it's important that the WD of WebIDL be automatically kept in sync with the ED (via Echidna/Travis or whatnot).

Until that's setup, I'm forced to object to a FPWD of WebIDL Level 2 being published, as it increases the likelihood of implementers accidentally implementing an outdated version of the spec.

**Comment by travisleithead** [comment]
The principle we used to publish Level 1, was that it only contained the stable, testable parts of the language. It looks like this FPWD is just a snapshot of a recent editor's draft--which I don't think reflects those principles exactly (e.g., the [AllowShared] for SharedArrayBuffer doesn't have wide testable deployment AFAIK. There are probably other things as well. Has any work been done to note what should be in/out?

**Comment by plehegar** [comment]
Note that since the FPWD publication isn't automatic, I can't get the automatic setup to work until the FPWD is published. I'm certainly willing to wait until all ducks are aligned in the row before publishing the FPWD but I don't think we should hold the CfC on that imho.

**Comment by tobie** [comment]
@travisleithead we've started being systematic about filing bugs for breaking changes with implementors, impacted specs, and tools: https://github.com/heycam/webidl/issues/labels/downstream-tracking

This might be helpful for what you have in mind.

Similarly, we're trying to keep idlharness up to date with the spec, which should help assess implementation status.

**Comment by tobie** [comment]
>  Note that since the FPWD publication isn't automatic, I can't get the automatic setup to work until the FPWD is published. I'm certainly willing to wait until all ducks are aligned in the row before publishing the FPWD […]

I just want to make sure that there's a PR ready against heycam/webidl and that @heycam has been looped in to setup the appropriate hooks before we move ahead with this.

A thumbs up from @heycam + a PR is all I need to rescind my objection. :)

**Comment by plehegar** [comment]
@tobie, note that the proposed pull request doesn't require any hooks.

**Comment by tobie** [comment]
We also really want to have `/tr/webidl/`point to the latest WD (i.e. the one), and thus it's not necessary to have both links to "Latest published version of Web IDL" and "Latest published version of Web IDL v2" in the header; we only want one such link, it should point to https://www.w3.org/TR/webidl/ where this WD should be hosted.

**Comment by plehegar** [comment]
Yes, the idea is to have /tr/webidl points to the WD. To align this with https://github.com/w3c/tr-pages/wiki/Latest-versions-proposal-for-leveled-specifications , we'd have /TR/webidl/ points to /TR/webidl/upcoming to be exact.

**Comment by tobie** [comment]
Good. Can we just keep one link, then: "Latest published version of Web IDL" and have it point to /TR/webidl/? I'm not opposed to keeping a link to V1, though I don't find that particularly useful, but I want to make sure V1 is clearly labeled as being the "old version". So something like, "Previous Recommendation," or something like that, if we must link to it.

**Comment by plehegar** [comment]
There is no link to V1 proposed. What I have is a link to webidl (which will points to the WD) and webidl-2 (which will also points to the WD).

**Comment by tobie** [comment]
Why would you want two links which point to the same thing?

**Comment by plehegar** [comment]
If we happen to do a webidl-3 , it wouldn't point to the same thing in the long run since /tr/webidl would keep following the tip.

**Comment by tobie** [comment]
When we've shipped level 3, what's the use case of someone navigating to level 2 REC from a WD of level 2? That seems like we're adding a lot of confusion for a very minor use case.

**Comment by plehegar** [comment]
You may want to comment on https://lists.w3.org/Archives/Public/spec-prod/2017JulSep/0005.html then. I'd be interested to know what other folks think as well.

**Comment by tobie** [comment]
> You may want to comment on https://lists.w3.org/Archives/Public/spec-prod/2017JulSep/0005.html then.

Sure, but I think that's orthogonal. The fact level-2 exists as a URL doesn't mean we should be pointing to if from within the spec.

**Comment by travisleithead** [comment]
It sounds like we'll have regular publication setup, which is good, but what criteria are we using to cut to Rec? I'd like to see something about this mentioned in the draft, so it's clear to folks how we intend to get there.

**Comment by LJWatson** [comment]
The CFC received objections, and so is closed without consensus.
