### ISSUE TITLE
to-be-deprecated standards market share and support in next-gen engines

### ISSUE THREAD

**Issue by cordovapolymer** [w3c/WebPlatformWG#92]
Is there a comprehensive research on market share of the HTML 3.2, 4.0, 4.01 и 5.0 HTML standards?

Also current web browsers have a compatibility layer which allows rendering of non-strict documents with violations of the standard, so these renderers will be aimed to handle such violations in any mid-future HTML engine. 
Of course the aim of W3C is to provide us with the specifications, but how are those specifications implemented is also has to be considered.

For the reasons mentioned, it would be great if a special document covering the differences, and limited implementation recommendation of the standards which are going to be deprecated to the current web standards would be created.

**Comment by bricss** [comment]
Totally agree ♻️

**Comment by cordovapolymer** [comment]
There is some data on the W3Techs on the market share:
> HTML5 | 84.8% 
> HTML transitional | 14.4%
> HTML strict  | 1.0%
> AMP  | less than 0.1%

but it's not detailed to the standard version https://w3techs.com/technologies/details/ml-html/all/all

**Comment by LJWatson** [comment]
@cordovapolymer, I'm sorry you didn't get a timely reply to your enquiry.

I don't know of any research into the useage of different versions of HTML. In the context of the decision to mark older versions of xHTML and HTML Obsolete and/or Superseded though, there is no intent to prevent existing sites/applications from using these technologies, only an intent to encourage new sites/apps to use the most up-to-date version of the language available.
