### ISSUE TITLE
TPAC agenda: Tue Nov 7 (Editing TF)

### ISSUE THREAD

**Issue by LJWatson** [w3c/WebPlatformWG#93]
This is a draft agenda. If you're a member of the WebPlat WG/Editing TF, please add specific items based on the available time slots.

If you plan to attend, please add a thumbs up to this comment.

* 9.30am: 
  * Input Events level 2 vs. hidden textarea based approach as only way to handle IME [1]
  * What input events can we make cancelable also in level 1 of the Input Events spec? (a higher number of cancelable events is proposed both in Input Events level 2 and teaxtarea-approach proposal [1] point E. 
  * Should we continue with plan of alternative contenteditable types? If yes, we need to figure out what to do about enabling disabling features? (see [2])
  * What attribute name should we use for feature-disabling/enabling?
* 10.30am: Break
* 11:00am: 
  * inputmode [3] and inputmode-action [4] (Dave Tapuska)
  * Yoichi: Selections with mutiple ranges (non-contiguous DOM Ranges) / Alexandre: Selections with mutiple ranges (one selection in hidden textarea and another onscreen aka "Splitting apart the text selection singleton")
* 12.30pm: Lunch
* 2pm: Meeting with APA WG:
  * Input Events
* 3pm: Clipboard API:
  * Async API for images (to allow the generation of clipboard content to be delayed)
  * Image formats for API (see [clipboard/44](https://github.com/w3c/clipboard-apis/issues/44))
  * other mimetypes
* 3.30pm: Break
* 4pm: 
  * Alexandre: Touch text selection “blue handles”
  * Alexandre: Floating action bar
  * Alexandre: Onscreen keyboard show/hide
  * Alexandre: Spellcheck and composition underlines
  * Alexandre: IME dropdown menu positioning
* 6.00pm: Close

For Remote Participants (WebEx meeting) see below

Other WebPlat meetings:
* Thu Nov 9 (WebPlat general): #94 
* Fri Nov 10 (Web Components): #95 

[1] https://docs.google.com/document/d/10qltJUVg1-Rlnbjc6RH8WnngpJptMEj-tyrvIZBPSfY/edit
[2] https://www.w3.org/2016/09/22-webapps-minutes.html#item16
[3] https://cdn.rawgit.com/dtapuska/inputmode/HEAD/index.html
[4] https://cdn.rawgit.com/dtapuska/action-hint/HEAD/index.html

**Comment by garykac** [comment]
We'll need some time to talk about the Clipboard API. 

Specifically (in order of priority):
* Async API for images (to allow the generation of clipboard content to be delayed)
* Image formats for API (see [clipboard/44](https://github.com/w3c/clipboard-apis/issues/44))
* other mimetypes

**Comment by LJWatson** [comment]
This should be ok. Ping @johanneswilm for a sense of when to put it on the agenda?

**Comment by yoichio** [comment]
I want to talk about multiple Ranges on [Selection API](http://w3c.github.io/selection-api/#dom-selection-getrangeat).

**Comment by johanneswilm** [comment]
@yoichio: I take it that what you want to talk about is something like making multiple selections available like they are on FF for content that is not visually presented in document order, etc., not multiple selections to have one selection in a hidden textarea and another in a dom element that is being shown for the kind of editor Alexandre is proposing?

**Comment by yoichio** [comment]
Yes. That is for representing not contiguous DOM Ranges mainly by user selection.
I know there are synchronous issues between DOM and IME, but it is another topic.

**Comment by johanneswilm** [comment]
@yoichio Ok, I have added it. I agree that it is a separate issue, but it probably needs to be discussed either just before or just after Alexandre's proposal of creating multiple selections, as the two will influence one-another if we decide to do both. Do you agree or should we make entirely different items at different times of these issues?

**Comment by yoichio** [comment]
I agree to discuss at the same.

**Comment by LJWatson** [comment]
Please note that meeting times are Pacific Standard Time (PST).

[Remote dial-in information](https://lists.w3.org/Archives/Member/w3c-archive/2017Nov/0059.html
) (member confidential.) If this is a problem, please email 
team-webplatform@w3.org.

**Comment by smaug----** [comment]
Which IRC channel will be used? #webapps? I may call in to some discussions.

**Comment by tomoyukilabs** [comment]
Now the IRC channel #webplat is used.

**Comment by LJWatson** [comment]
With thanks to everyone who took part, the [meeting minutes](https://www.w3.org/2017/11/07-editing-minutes.html) are available.
