### ISSUE TITLE
TPAC agenda: Thu Nov 9 (WebPlat general)

### ISSUE THREAD

**Issue by LJWatson** [w3c/WebPlatformWG#94]
This is a draft agenda. If you're a member of Web Platform please request changes by posting a comment.

Please indicate attendance by adding a thumbs up to this comment.

* 9.30am: HTML (45 mins)
* 10.15am: Workers (15 mins)
* 10.30am: Break
* 11am: Meeting with WICG (60 mins):
  * [Asynchronous JavaScript Cookies API](https://github.com/WICG/async-cookies-api/) and [Cookie Change Events](https://github.com/patrickkettner/cookie-change-events)
  * [Accessibility Object Model (AOM)](https://github.com/WICG/aom)
  * [File/Directory Entries API](https://github.com/WICG/entries-api/)
* 12pm: Screen Orientation API (15 mins)
* 12.15pm: IndexedDB API (15 mins)
* 12.30pm: Lunch
* 2pm: Intersection Observer (30 mins)
* 2.30pm: Pointer Lock 2.0 (30 mins)
* 3pm: UI Events (30 mins)
* 3.30pm: Break
* 4pm: Web App Manifest (15 mins)
* 4.15pm: WebIDL Level 2 (15 mins)
* 4.30pm: Gamepad API (30 mins)
* 5pm: TBC
* 5.30pm: Close

For Remote Participants (WebEx meeting) please see below

Other WebPlat meetings:
* Tue Nov 7 (Editing TF): #93 
* Fri Nov 10 (Web Components): #95

**Comment by mikewest** [comment]
@LJWatson, et al: Perhaps we could squeeze a discussion of the [Workers spec maintenance](https://github.com/w3c/html/issues/187#issuecomment-333670539) into the HTML section?

**Comment by chaals** [comment]
Seems reasonable, although we might be able to deal with it offline. It doesn't seem like a long topic anyway, unless we just want to vent about the problems we have had.

**Comment by LJWatson** [comment]
@MikeWest have set aside 15 mins from the HTML block. Does that sound about right?

**Comment by mikewest** [comment]
@LJWatson: I don't think we'll need 15 minutes, but I'd indeed appreciate y'all carving out some small period of time to talk about the current maintenance commitments and whether there's something we could do as a group to a) reduce the delta between implementations and the W3C document, and b) keep the delta down in the future. As-is, folks who land on the W3C spec for workers are not being well served. 

(And if y'all'd prefer having that discussion offline or on the mailing list to save F2F time, I'm happy to move to your venue of choice. :) )

**Comment by LJWatson** [comment]
@MikeWest it'd be good to discuss this in person, but if you could frame the question/points for discussion by opening an issue on [Workers](https://github.com/w3c/workers) that'd be helpful. Thanks.

**Comment by knyg** [comment]
I'd like to add that Steve Agoston and I (Kelvin Yong) are interested in observing Thursday's meeting in anticipation of joining the WebPlatform WG.

**Comment by inexorabletash** [comment]
I should give a status update for [File/Directory Entries API](https://github.com/WICG/entries-api/) during the WICG session (the 11am slot). 5-10 minutes.

**Comment by LJWatson** [comment]
Please note that meeting times are Pacific Standard Time (PST).

[Remote dial-in information](https://lists.w3.org/Archives/Member/w3c-archive/2017Nov/0059.html
) (member confidential.) If this is a problem, please email 
team-webplatform@w3.org.

**Comment by LJWatson** [comment]
Thanks @inexorabletash, have added it to the agenda ^^.

**Comment by nolanlawson** [comment]
Next to async cookies, could you please also add a link to [Cookie Change Events](https://github.com/patrickkettner/cookie-change-events)? We'd like to discuss both APIs in the same slot.

**Comment by LJWatson** [comment]
@nolanlawson done.

**Comment by LJWatson** [comment]
With thanks to everyone who took part, the [meeting minutes](https://www.w3.org/2017/11/09-webplat-minutes.html
) are now available.
