### ISSUE TITLE
TPAC agenda: Fri Nov 10 (Web Components)

### ISSUE THREAD

**Issue by LJWatson** [w3c/WebPlatformWG#95]
This is a draft agenda. If you're a member of the WebPlat WG/Web Components, please add specific items based on the available time slots.

Please indicate attendance by adding a thumbs up to this comment.
* 9.30am: Web Components
* 10.30am: Break
* 11am: Meeting with ARIA WG:
  * Web Components + ARIA 2.0
* 12.30pm: Lunch
* 2pm: Web Components
* 3.30pm: Break
* 4pm: Web Components
* 5.30pm: Close

For Remote Participants (WebEx meeting) please see below
For IRC, use #webplat
Other WebPlat WG meetings:
* Tue Nov 7 (Editing TF): #93
* Thu Nov 9 (WebPlat general): #94

**Comment by TakayoshiKochi** [comment]
Thanks Léonie!

FYI web components agenda is already being discussed at its own thread: https://github.com/w3c/webcomponents/issues/641
For more detailed agenda/priority I'd recommend discuss slots there first, based on allocated time here.

**Comment by LJWatson** [comment]
Please note that meeting times are Pacific Standard Time (PST).

[Remote dial-in information](https://lists.w3.org/Archives/Member/w3c-archive/2017Nov/0059.html
) (member confidential.) If this is a problem, please email 
team-webplatform@w3.org.

**Comment by Jxck** [comment]
I found [meeting minutes](https://www.w3.org/2017/11/10-webplat-minutes.html) for this.

**Comment by LJWatson** [comment]
Thanks @Jxck. You beat us to it.

With thanks to everyone who participated.
