### ISSUE TITLE
Mark ElementTraversal Rec as obsolete

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/WebPlatformWG#96]
As far as I can tell, https://www.w3.org/TR/ElementTraversal/ has been incorporated into newer versions of the DOM specs. Can we make it so that the TR page reflects this? (I'm not sure if this means going through the Obsolescence process or something else)

**Comment by chaals** [comment]
Yes, I think it makes sense to state that this has been superseded through the obsolete rec process. I'll propose a CfC

**Comment by xfq** [comment]
Maybe we can mark previous versions of DOM obsolete too.

The specifications include:

* [Document Object Model (DOM) Level 1 Specification](https://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/)
* [Document Object Model (DOM) Level 2 Core Specification](https://www.w3.org/TR/2000/REC-DOM-Level-2-Core-20001113/)
* [Document Object Model (DOM) Level 2 Views Specification](https://www.w3.org/TR/2000/REC-DOM-Level-2-Views-20001113/)
* [Document Object Model (DOM) Level 2 Style Specification](https://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/)
* [Document Object Model (DOM) Level 2 Events Specification](https://www.w3.org/TR/2000/REC-DOM-Level-2-Events-20001113/)
* [Document Object Model (DOM) Level 2 Traversal and Range Specification](https://www.w3.org/TR/2000/REC-DOM-Level-2-Traversal-Range-20001113/)
* [Document Object Model (DOM) Level 2 HTML Specification](https://www.w3.org/TR/2003/REC-DOM-Level-2-HTML-20030109/)
* [Document Object Model (DOM) Level 3 Core Specification](https://www.w3.org/TR/2004/REC-DOM-Level-3-Core-20040407/)
* [Document Object Model (DOM) Level 3 Validation Specification](https://www.w3.org/TR/2004/REC-DOM-Level-3-Val-20040127/)
* [Document Object Model (DOM) Level 3 Load and Save Specification](https://www.w3.org/TR/2004/REC-DOM-Level-3-LS-20040407/)
* [Element Traversal Specification](https://www.w3.org/TR/2008/REC-ElementTraversal-20081222/)
* [Selectors API Level 1](https://www.w3.org/TR/2013/REC-selectors-api-20130221/)

New implementations should follow the following specifications:

* DOM
* UI Events *
* CSSOM
* HTML
* Selectors
* Maybe others?

**Comment by LJWatson** [comment]
@Chaals did this CFC go out? I can't find it, but our CFC can happen in a multitude of places, so I'm probably looking in the wrong place.

@XFQ I think it makes sense to wait until the outcome of the W3C/WHATWG negotiations before we take steps to render older versions of DOM Obsolete and/or Superseded.

**Comment by LJWatson** [comment]
@XFQ unless ElementTraversal has been incorporated into both the W3C DOM spec and the WHATWG HTML/DOM spec, in which case the original spec is probably Obsolete either way?

**Comment by xfq** [comment]
@LJWatson All five attributes of the `ElementTraversal` interface are in WHATWG DOM and W3C DOM now, so I think it's superseded by the DOM spec.

**Comment by xfq** [comment]
[Selectors API Level 1](https://www.w3.org/TR/2013/REC-selectors-api-20130221/) can also be obsoleted/superseded. `querySelector` and `querySelectorAll` are now defined in both DOM specs, and the algorithms in [6.4. Processing Selectors](https://www.w3.org/TR/2013/REC-selectors-api-20130221/#processing-selectors) are defined in the [Selectors](https://www.w3.org/TR/selectors-4/) spec.

**Comment by marcoscaceres** [comment]
Moved here: https://github.com/w3ctag/obsoletion/issues/4
