### ISSUE TITLE
[Feature Request] pause/resume webdriver

### ISSUE THREAD

**Issue by edurenye** [w3c/WebPlatformWG#98]
From this issue in Selenium: SeleniumHQ/selenium#5269
@p0deje said that it has to be implemented in drivers and is outside of Selenium, and that the right place to file the issue was in the [wevdriver specs](http://goo.gl/LxCtcV). But then I saw that IndieUI is deprecated now and WebPlataformWG has taken the role of IndieUI Events, so I think that the right place to file the issue is here.

So we need to add a Event to pause/resume the execution of the website, everything from JS to HTML requests, to DOM loading.

**Comment by LJWatson** [comment]
This seems like an issue for [Web Driver](https://www.w3.org/TR/webdriver/) itself. Suggest filing it on the [Web Driver repo](https://github.com/w3c/webdriver).

**Comment by edurenye** [comment]
Ok, thanks. I opened an issue there: w3c/webdriver#1199
